mutation CreatePostCardTextPost($input: TextPostInput!) {
  createTextPost(input: $input) {
    id
  }
}
mutation CreatePostCardImagePost($input: ImagePostInput!) {
  createImagePost(input: $input) {
    id
  }
}
