query Notifications {
  notifications {
    id
    ...on FriendshipRequestNotification {
      from {
        id
        firstName
        avatarURL
      }
      date
    }
    ...on PostLikedNotification {
      liker {
        id
        firstName
        avatarURL
      }
      date
      post {
        id
      }  
    }
  }
}

subscription NotificationsNewNotification {
  newNotification{
    id
  }
}