query NotificationButton {
  notifications {
    id
    ...on FriendshipRequestNotification {
      from {
        id
        name
        avatarURL
      }
      date
    } 
  }
}

subscription NotificationButtonNewNotification {
  newNotification{
    id
  }
}