query HomePagePosts {
  me {
    id
    name
    online
  }
  posts {
    id
    text
    createdAt
    liked
    user {
      id
      name
    }
    likedBy {
      id
      firstName
    }
    comments {
      text
      createdAt
      user {
        id
        name
        online
      }
    }
  }
}
