query HomePage {
  me {
    id
    name
    firstName
    online
  }
  posts {
    __typename
    id
    text
    createdAt
    liked
    user {
      id
      online
      avatarURL
      name
    }
    likedBy {
      id
      firstName
    }
    comments {
      text
      createdAt
      user {
        avatarURL
        id
        name
        online
      }
    }
    ... on ImagePost {
      imageURL
    }
  }
}
