query ProfileDetailPage($userID: ID!) {
  user(id: $userID) {
    id
    name
    status
    online
    birthday
    friendshipStatus
    friends {
      id
      name
      online
    }
  }
}

mutation ProfileDetailPageRequestFriendship($userID: ID!) {
  requestFriendship(id: $userID) {
    id
  }
}
