query ProfileDetailPage($userID: ID!) {
  user(id: $userID) {
    id
    name
    status
    online
    birthday
    friendshipStatus
    avatarURL
    city
    hobbies
    job {
      company
      position
    }
    friends {
      id
      name
      online
    }
  }
  posts: postsOfUser(id: $userID) {
    __typename
    id
    text
    createdAt
    liked
    user {
      id
      online
      avatarURL
      name
    }
    likedBy {
      id
      firstName
    }
    comments {
      text
      createdAt
      user {
        avatarURL
        id
        name
        online
      }
    }
    ... on ImagePost {
      imageURL
    }
  }
  me {
    id
    name
    online
  }
}

mutation ProfileDetailPageRequestFriendship($userID: ID!) {
  requestFriendship(id: $userID) {
    id
    to {
      id
      friendshipStatus
    }
  }
}
